import { Metadata } from 'next'
import LoginForm from '@/components/Form/LoginForm'

export const metadata: Metadata = {
  title: 'Login Page',
  description: 'Generated by create next app'
}

export default function LoginPage() {
  return (
    <section className="w-full sm:w-[450px] mx-auto">
      <LoginForm />
    </section>
  )
}
