import { Metadata } from 'next'
import Login from '@/components/Login'
import Verify from '@/components/Verify'
import { handleGithubLogin } from '@/lib/actions'
import { Button } from '@/components/ui/button'
import { Facebook, Github } from 'lucide-react'
import { CardFooter } from '@/components/ui/card'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Login Page',
  description: 'Generated by create next app'
}

export default function LoginPage() {
  return (
    <section className="w-full sm:w-[450px] mx-auto">
      <Verify
        label="login"
        renderFooter={() => (
          <CardFooter className="justify-center">
            <Button
              variant={'link'}
              className="tracking-tight p-0"
              size={'sm'}
              asChild
            >
              <Link href={'/auth/register'}>
                Don't have an account? Register
              </Link>
            </Button>
          </CardFooter>
        )}
      >
        <form action={handleGithubLogin}>
          <Button
            aria-label="Login with Github"
            variant={'secondary'}
            type="submit"
            className="w-full"
          >
            <Github className="mr-2 h-4 w-4" /> Login with Github
          </Button>
        </form>
        <Button variant={'secondary'} aria-label="Login with Google">
          <Facebook className="mr-2 h-4 w-4" /> Login with Facebook
        </Button>
        <p className="text-center font-medium">OR</p>
      </Verify>
    </section>
  )
}
