import SettingsForm from '@/components/Form/SettingsForm'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Settings Page',
  description: 'Generated by create next app'
}

export default function SettingsPage() {
  return (
    <section className="w-full sm:w-[450px] mx-auto">
      <SettingsForm />
    </section>
  )
}
