import { Metadata } from 'next'
import ResetPasswordForm from '@/components/Form/ResetPasswordForm'

export const metadata: Metadata = {
  title: 'Forgot Password Page',
  description: 'Generated by create next app'
}

export default function ResetPage() {
  return (
    <section className="w-full sm:w-[450px] mx-auto">
      <ResetPasswordForm />
    </section>
  )
}
