import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/providers/ThemeProvider'
import NavBar from '@/components/Nav/NavBar'
import Footer from '@/components/Footer'
import { Toaster } from '@/components/ui/toaster'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/lib/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: {
    default: 'Next Blog',
    template: '%s | Next Blog'
  },
  description: 'Generated by create next app',
  manifest: '/manifest.webmanifest'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <div className="container w-full min-h-screen flex flex-col justify-between">
            <SessionProvider session={session}>
              <NavBar />
              {children}
              <Footer />
            </SessionProvider>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
