import AdminAddList from '@/components/AdminAddList'
import { Separator } from '@/components/ui/separator'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Admin Page',
  description: 'Generated by create next app'
}

export default function AdminPage() {
  return (
    <section className="py-16">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        <AdminAddList label="user" />
      </div>
      <Separator className="my-14" />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        <AdminAddList label="post" />
      </div>
    </section>
  )
}
