import AdminDashboard from '@/components/Admin/AdminDashboard'
import AdminItem from '@/components/Admin/AdminItem'
import { Separator } from '@/components/ui/separator'
import { getPosts } from '@/data/post'
import { getUsers } from '@/data/user'
import { removePost, removeUser } from '@/lib/actions'
import { type TBlogPost, type TUserPost } from '@/lib/types'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Admin Page',
  description: 'Generated by create next app'
}

export default function AdminPage() {
  return (
    <section className="py-16">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        <AdminDashboard
          label="user"
          getItems={getUsers}
          renderItems={(data: TUserPost[]) =>
            data.map((user) => (
              <AdminItem
                key={user._id}
                id={user._id.toString()}
                href={`/user/${user._id}`}
                showTooltip
                img={user?.img}
                title={user.username}
                onDelete={removeUser}
              />
            ))
          }
        />
      </div>
      <Separator className="my-14" />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
        <AdminDashboard
          label="post"
          getItems={getPosts}
          renderItems={(data: TBlogPost[]) =>
            data.map((post) => (
              <AdminItem
                key={post.slug}
                href={`/blog/${post.slug}`}
                img={post?.img}
                id={post._id.toString()}
                title={post.title}
                onDelete={removePost}
              />
            ))
          }
        />
      </div>
    </section>
  )
}
