import { Metadata } from 'next'
import ForgotPasswordForm from '@/components/Form/ForgotPasswordForm'

export const metadata: Metadata = {
  title: 'Forgot Password Page',
  description: 'Generated by create next app'
}

export default function LoginPage() {
  return (
    <section className="w-full sm:w-[450px] mx-auto">
      <ForgotPasswordForm />
    </section>
  )
}
