import BlogPost from '@/components/BlogPost'
import { getPosts } from '@/lib/data'
import { type TBlogPost } from '@/lib/types'
import { Metadata } from 'next'
import React, { Suspense } from 'react'
import Loading from './loader'

export const metadata: Metadata = {
  title: 'Blog Page',
  description: 'Generated by create next app'
}

export default async function BlogPage() {
  const posts: TBlogPost[] = await getPosts()

  return (
    <>
      <section className="py-10">
        <Suspense fallback={<Loading />}>
          {posts?.length ? (
            <div className="flex flex-wrap gap-2 md:gap-8 items-start">
              {posts.map((post, i) => (
                <BlogPost post={post} key={i} />
              ))}
            </div>
          ) : (
            <div className="text-lg font-semibold text-center">
              No posts here yet &#128580;
            </div>
          )}
        </Suspense>
      </section>
    </>
  )
}
