import BlogPost from '@/components/BlogPost'
import { type TBlogPost } from '@/lib/types'
import { Metadata } from 'next'
import React, { Suspense } from 'react'
import Loading from './loader'
import { getPosts } from '@/data/post'

export const metadata: Metadata = {
  title: 'Blog Page',
  description: 'Generated by create next app'
}

export default async function BlogPage() {
  const posts: TBlogPost[] = await getPosts()
  const rowsCount = 3

  function setBlogGrid() {
    const rows: TBlogPost[][] = Array.from({ length: rowsCount }, () => [])
    for (let i = 0; i < posts.length; i++) {
      rows[i % rowsCount].push(posts[i])
    }
    return rows
  }

  const rows = setBlogGrid()

  return (
    <>
      <section className="py-10">
        <Suspense fallback={<Loading />}>
          {posts?.length ? (
            <div className="flex flex-wrap gap-2 md:gap-8 items-start">
              {rows.map((row, i) => (
                <div className="flex-1 flex flex-col gap-5" key={i}>
                  {row.map((post, k) => (
                    <BlogPost post={post} key={k} />
                  ))}
                </div>
              ))}
            </div>
          ) : (
            <div className="text-lg font-semibold text-center">
              No posts here yet &#128580;
            </div>
          )}
        </Suspense>
      </section>
    </>
  )
}
