import VerifyEmailForm from '@/components/Form/VerifyEmailForm'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Verify Email Page',
  description: 'Generated by create next app'
}

export default function VerifyPage() {
  return (
    <section className="w-full sm:w-[450px] mx-auto">
      <VerifyEmailForm />
    </section>
  )
}
